# Generated by Django 3.0.2 on 2020-01-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('image', models.FilePathField(path='/img')),
                ('github', models.URLField(blank=True, default='')),
                ('production', models.URLField(blank=True, default='')),
                ('technologies', models.ManyToManyField(blank=True, default='', related_name='projects', to='projects.Technology')),
            ],
        ),
    ]
